export const Country = Object.freeze({
    AF: 'Afganistán',
    AL: 'Albania',
    DE: 'Alemania',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antártida',
    AG: 'Antigua y Barbuda',
    SA: 'Arabia Saudí',
    DZ: 'Argelia',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaiyán',
    BS: 'Bahamas',
    BH: 'Bahréin',
    BD: 'Bangladés',
    BB: 'Barbados',
    BE: 'Bélgica',
    BZ: 'Belice',
    BJ: 'Benín',
    BM: 'Bermudas',
    BY: 'Bielorrusia',
    BO: 'Bolivia',
    BA: 'Bosnia-Herzegovina',
    BW: 'Botsuana',
    BR: 'Brasil',
    BN: 'Brunéi',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    BT: 'Bután',
    KH: 'Camboya (Antes Kampuchea)',
    CM: 'Camerún',
    CA: 'Canadá',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CY: 'Chipre',
    VA: 'Ciudad del Vaticano',
    CO: 'Colombia',
    CG: 'Congo',
    KP: 'Corea del Norte',
    KR: 'Corea del Sur',
    CI: 'Costa de Marfil',
    CR: 'Costa Rica',
    HR: 'Croacia',
    CU: 'Cuba',
    CW: 'Curaçao',
    DK: 'Dinamarca',
    DM: 'Dominica',
    EC: 'Ecuador',
    EG: 'Egipto',
    SV: 'El Salvador',
    AE: 'Emiratos Árabes Unidos',
    ER: 'Eritrea',
    SK: 'Eslovaquia',
    SI: 'Eslovenia',
    ES: 'España',
    US: 'Estados Unidos de América',
    EE: 'Estonia',
    ET: 'Etiopía',
    FM: 'Federación de Estados Micronesia',
    PH: 'Filipinas',
    FI: 'Finlandia',
    FJ: 'Fiyi',
    FR: 'Francia',
    GA: 'Gabón',
    GM: 'Gambia',
    GE: 'Georgia',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GD: 'Granada',
    GR: 'Grecia',
    GL: 'Groenlandia',
    GP: 'Guadalupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GY: 'Guayana',
    GF: 'Guayana Francesa',
    GG: 'Guernsey',
    GN: 'Guinea',
    GQ: 'Guinea Ecuatorial',
    GW: 'Guinea-Bissau',
    HT: 'Haití',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungría',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Irán',
    IQ: 'Iraq',
    IE: 'Irlanda',
    IM: 'Isla de Man',
    IS: 'Islandia',
    KY: 'Islas Caimán',
    CC: 'Islas Cocos',
    KM: 'Islas Comores',
    CK: 'Islas Cook',
    FO: 'Islas Feroe',
    MV: 'Islas Maldivas',
    FK: 'Islas Malvinas (Falkland)',
    MP: 'Islas Marianas del Norte',
    MH: 'Islas Marshall',
    UM: 'Islas menores alejadas EE. UU.',
    PN: 'Islas Pitcairn',
    SB: 'Islas Salomón',
    SJ: 'Islas Svalbard y Jan Mayen',
    TC: 'Islas Turcas y Caicos',
    VG: 'Islas Vírgenes Británicas',
    VI: 'Islas Vírgenes de los EE. UU.',
    WF: 'Islas Wallis y Futuna',
    IL: 'Israel',
    IT: 'Italia',
    JM: 'Jamaica',
    JP: 'Japón',
    JE: 'Jersey (Islas Anglonormandas)',
    JO: 'Jordania',
    KZ: 'Kazajistán',
    KE: 'Kenia',
    KG: 'Kirguistán',
    KI: 'Kiribati',
    XK: 'Kosovo',
    KW: 'Kuwait',
    LA: 'Laos',
    LS: 'Lesoto',
    LV: 'Letonia',
    LB: 'Líbano',
    LR: 'Liberia',
    LY: 'Libia',
    LI: 'Liechtenstein',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    MO: 'Macao',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MY: 'Malasia',
    MW: 'Malaui',
    ML: 'Mali',
    MT: 'Malta',
    MA: 'Marruecos',
    MQ: 'Martinica',
    MU: 'Mauricio',
    MR: 'Mauritania',
    YT: 'Mayotte',
    MX: 'México',
    MD: 'Moldavia',
    MC: 'Mónaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MZ: 'Mozambique',
    MM: 'Myanmar (antigua Birmania)',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NI: 'Nicaragua',
    NE: 'Níger',
    NG: 'Nigeria',
    NU: 'Niue',
    NO: 'Noruega',
    NC: 'Nueva Caledonia',
    NZ: 'Nueva Zelanda',
    XJ: 'Oceanía Neozelandesa',
    OM: 'Omán',
    XI: 'ORGANISMOS INTERNACIONALES',
    QU: 'Países / Territ. No Determinados',
    NL: 'Países Bajos',
    PK: 'Pakistán',
    PW: 'Palaos',
    PS: 'Palestina',
    PA: 'Panamá',
    PG: 'Papúa Nueva Guinea',
    PY: 'Paraguay',
    PE: 'Perú',
    PF: 'Polinesia Francesa',
    PL: 'Polonia',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    GB: 'Reino Unido',
    CF: 'República Centroafricana',
    CZ: 'República Checa',
    CV: 'República de Cabo Verde',
    CD: 'República Democrática del Congo',
    DO: 'República Dominicana',
    RE: 'Reunión',
    RW: 'Ruanda',
    RO: 'Rumanía',
    RU: 'Rusia',
    AS: 'Samoa Americana',
    WS: 'Samoa Occidental',
    KN: 'San Cristóbal y Nieves',
    SM: 'San Marino',
    PM: 'San Pedro y Miquelón',
    VC: 'San Vicente y Granadinas',
    SH: 'Santa Elena y dependencias',
    LC: 'Santa Lucía',
    ST: 'Santo Tomé y Príncipe',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leona',
    SG: 'Singapur',
    SY: 'Siria',
    SO: 'Somalia',
    LK: 'Sri Lanka',
    SZ: 'Suazilandia',
    ZA: 'Sudáfrica',
    SD: 'Sudán',
    SE: 'Suecia',
    CH: 'Suiza',
    SR: 'Surinam',
    TH: 'Tailandia',
    TW: 'Taiwán',
    TZ: 'Tanzania',
    TJ: 'Tayikistán',
    IO: 'Territorio Británico Océano Índico',
    TL: 'Timor Oriental',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad y Tobago',
    TN: 'Túnez',
    TM: 'Turkmenistán',
    TR: 'Turquía',
    TV: 'Tuvalu',
    UA: 'Ucrania',
    UG: 'Uganda',
    UY: 'Uruguay',
    UZ: 'Uzbequistán',
    VU: 'Vanuatu',
    VE: 'Venezuela',
    VN: 'Vietnam',
    YE: 'Yemen',
    DJ: 'Yibuti',
    ZM: 'Zambia',
    ZW: 'Zimbabue',
});

export const CountryCodes = Object.keys(Country);
